
package nic.transport.homologation.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "dataportws", targetNamespace = "http://service.web.homologation.transport.nic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dataportws {


    /**
     * 
     * @param engineNo
     * @param chassisNo
     * @param transactionPass
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChassisInfo", targetNamespace = "http://service.web.homologation.transport.nic/", className = "nic.transport.homologation.web.service.GetChassisInfo")
    @ResponseWrapper(localName = "getChassisInfoResponse", targetNamespace = "http://service.web.homologation.transport.nic/", className = "nic.transport.homologation.web.service.GetChassisInfoResponse")
    @Action(input = "http://service.web.homologation.transport.nic/dataportws/getChassisInfoRequest", output = "http://service.web.homologation.transport.nic/dataportws/getChassisInfoResponse")
    public String getChassisInfo(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "transactionPass", targetNamespace = "")
        String transactionPass,
        @WebParam(name = "chassisNo", targetNamespace = "")
        String chassisNo,
        @WebParam(name = "engineNo", targetNamespace = "")
        String engineNo);

}
